### ISSUE TITLE
What is the private folder?

### ISSUE THREAD

**Issue by feijoes** [SwiftCODA/R6-API#5]
Hello,

I've been working on a personal project using this codebase, and I noticed that after compiling, the project automatically generates a private folder (as shown in the screenshot). From the name, I assume this folder should not be committed, but I didn't find it listed in the .gitignore file, so I'm unsure.

![imagen](https://github.com/SwiftCODA/R6-API/assets/74252371/05225972-2587-4975-91ed-edd06c210f8c)

I've tried looking for more information within the project, but explanations seem limited. Additionally, after compilation, I see this message:

```
Cluster: Forking 8 workers.
Cluster: Created worker.
Cluster: Created worker.
....
```
Should I be concerned about this? Sometimes it shows 6 workers, and other times it's 8.

Could you provide guidance on whether the private folder should be ignored in version control and any insights on the cluster behavior after compilation?

Thank you!

**Comment by SwiftCODA** [comment]
You're right, the private folder should not be committed. Depending on how serious your project is, I would also suggest not committing your Ubisoft credentials either, but it's up to you. This repo will really only work well on a small scale so I'm sure there isn't too much to worry about.

**Comment by SwiftCODA** [comment]
Regarding the number of cluster workers not always matching the number that it says it will fork...

You don't need to worry about it. The project is completely fine to run on a single worker/core. Clustering just lets it distribute workload amongst different cores and allows a new worker to be created automatically in the event of a fatal error. From my research, it looks like this can happen if there are other Node instances running. But, again, not a big deal.

**Comment by feijoes** [comment]
Ok Thanks

**Comment by SwiftCODA** [comment]
Added private to .gitignore in 29664b6.
